### ISSUE TITLE
Logging configuration not working

### ISSUE THREAD

**Issue by nielsvanhooy** [starlite-api/starlite-pg-redis-docker#101]
Dear,

i was checking this repo out (its awesome btw).
but i get the sense the logging config is not correctly working.

for example i tried to change:

formatters={"standard": {"format": "%(levelname)s - %(asctime)s - %(name)s - %(funcName)s - %(message)s"}},

to 
formatters={"standard": {"format": "%(asctime)s loglevel=%(levelname)-6s logger=%(name)s %(funcName)s() L%(lineno)-4d %(message)s"}}

but i do not see these changes reflected.

it could be on my end (got a little bit of a knowledge gap in python loggers.

let me know if you see the same.

kind regards,
Niels

**Comment by nielsvanhooy** [comment]
can be closed. 
changed:

root={"level": settings.app.LOG_LEVEL, "handlers": ["queue_listener"]},

to

root={"level": settings.app.LOG_LEVEL, "handlers": ["queue_listener", "console"]},

and then i had the corrent output :)

**Comment by peterschutt** [comment]
Hey @nielsvanhooy - I've been experimenting with this for the last hour or so, thanks for the update!

> root={"level": settings.app.LOG_LEVEL, "handlers": ["queue_listener", "console"]},

This is what the starlite logging config does by default as well, see: https://github.com/starlite-api/starlite/blob/f97b5b210738fb8b9230faed4f44b7aa146e44ae/starlite/config/logging.py#L135

I'm trying to reconcile why that is necessary, given that `"console"` logger is a `StreamHandler` and the queue listener is too: https://github.com/starlite-api/starlite/blob/f97b5b210738fb8b9230faed4f44b7aa146e44ae/starlite/logging/standard.py#L23

I'm thinking this is something to do with `StringIO()` being passed to the `StreamHandler` as the stream.

**Comment by nielsvanhooy** [comment]
Hi @peterschutt 

Thanks for looking further into it i wouldn't had figured this out myself.
i also see the pull request in the starlite repo.

Thanks for your time and effort in this.

**Comment by peterschutt** [comment]
No worries, thanks for the issue, and I updated the app to use your format, having line number in there is better!

Just updated to starlite v1.28 and seems to be working :+1:
