### ISSUE TITLE
Cleanup in the Dockerfile is wrong

### ISSUE THREAD

**Issue by danielgafni** [starlite-api/starlite-pg-redis-docker#123]
Docker images store all the layers inside, so the current "cleanup" doesn't reduce the image she. Actually, it's doing the opposite, by adding negative deltas to the image. So the images ends up having both layers with the files created and then removed. 

For a files cleanup to work as intended the delete command has to be executed in the same RUN command as the command that creates these files. 

Some options to consider for reducing image size: 

1. Run poetry install with --no-cache
2. Use a multi stage build (as I can see there are attempts to do it already, except the current implementation just chains a few FROMs which doesn't do anything). 
3. Have persistent Poetry cache stored outside of the image by using Docker BuildKit build caching.

I can provide a better Dockerfile if needed.

**Comment by peterschutt** [comment]
Hi @danielgafni, thanks for the report!

This Dockerfile is based on [this](https://gist.github.com/Goldziher/942f4a027a7fa1e2cafaa35e0333b6dc). Originally there was a much more rudimentary, single-stage Dockerfile in the project that was certainly not ideal either.

Perfecting this would be a very welcome contribution!

**Comment by Goldziher** [comment]
@danielgafni would you like to submit a PR?

**Comment by danielgafni** [comment]
Totally forgot about this one:( 

I'm currently on vacation, will be able to do it in a week or so!
