### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite-pg-redis-docker#21]
I'd like to put `starlite` in the name of the application - I think that makes sense to do.

Some alternatives:

- `starlite-pg-docker`
- `example-starlite-pg-docker`
- `starlite-pg-docker-example`

Out of those I like the 3rd one most I think, but I'm open to suggestion.

**Comment by Goldziher** [comment]
Go ahead, all three are good

**Comment by peterschutt** [comment]
@Goldziher doesn't look like I have the permissions to be able to do this myself. I was going to go with `starlite-pg-redis-docker`. Not the most imaginative of names, but accurately describes the stack.

**Comment by Goldziher** [comment]
Ok, I'll grant you ownership of the repo

**Comment by Goldziher** [comment]
done
