### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite-pg-redis-docker#24]
I'd like to suggest to move the files from `/src/app` to simply `/app` or `/src`. Current structure is IMO a bit redundant, and it also requires pointing at src as root for imports to work correctly.

**Comment by peterschutt** [comment]
Yep, sure. I've forked off for our internal stuff. TBH, I'm looking forward to going through this project and refactoring with some different tooling to what we use here.

**Comment by peterschutt** [comment]
Done in #53
