### ISSUE TITLE
Cleanup items

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite-pg-redis-docker#58]
- [x] change `schema` and `model` service object class vars to `schema_type` and `model_type`. This reduces incidence of name clashes with `schema` and `model` module names.
- [x] perhaps the service object having a reference to the model type and being generic on the model type is unnecessary - the generic reference to the repository type should be enough, I think.
- [x] update the orm usage to proper 2.0 patterns including use of `mapped_column()`: https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models
- [x] move the scripts from the utils folder outside of the app folder completely, maybe into the scripts folder
- [x] move constants into their own file, and use a string enum for paths
- [x] move the restartable worker class into a lib folder outside of the app folder - seperate the code.
- [x] update sonar.properties (whatever the file is called) to reflect these changes
- [x] test cov

**Comment by Goldziher** [comment]
I also suggest the following:

1. move the scripts from the `utils` folder outside of the `app` folder completely,  maybe into the `scripts` folder
2. move constants into their own file, and use a string enum for paths
3. move the restartable worker class into a lib folder outside of the app folder - seperate the code. 
4. update sonar.properties (whatever the file is called) to reflect these changes

**Comment by peterschutt** [comment]
Have added to the list.

Do you know if it is possible to add github dependencies in pre-commit `additional_dependencies` section?

**Comment by Goldziher** [comment]
> Have added to the list.
> 
> Do you know if it is possible to add github dependencies in pre-commit `additional_dependencies` section?

What dependencies?

**Comment by peterschutt** [comment]
> > Have added to the list.
> > 
> > Do you know if it is possible to add github dependencies in pre-commit `additional_dependencies` section?
> 
> What dependencies?

Sqlalchemy

**Comment by Goldziher** [comment]
Sure

**Comment by peterschutt** [comment]
Just list the repo url?

**Comment by Goldziher** [comment]
I think so. It's basically pip

**Comment by peterschutt** [comment]
Yep, same as pip need the `git+`, e.g., `"git+https://github.com/sqlalchemy/sqlalchemy"`

**Comment by Goldziher** [comment]
I resovled all issues in the above PR
