### ISSUE TITLE
Feature: include SAQ async worker pattern

### ISSUE THREAD

**Issue by peterschutt** [starlite-api/starlite-pg-redis-docker#65]

**Comment by grillazz** [comment]
@peterschutt what you think about https://arq-docs.helpmanual.io/ ?

**Comment by peterschutt** [comment]
I particularly like that SAQ doesn't rely on long polling to discover jobs. This is from their readme:

## Comparison to ARQ
SAQ is heavily inspired by [ARQ](https://github.com/samuelcolvin/arq) but has several enhancements.

1. Avoids polling by leveraging [BLMOVE](https://redis.io/commands/blmove) or [RPOPLPUSH](https://redis.io/commands/rpoplpush) and NOTIFY
    1. SAQ has much lower latency than ARQ, with delays of < 5ms. ARQ's default polling frequency is 0.5 seconds
	  2. SAQ is up to [8x faster](benchmarks) than ARQ
2. Web interface for monitoring queues and workers
3. Heartbeat monitor for abandoned jobs
4. More robust failure handling
    1. Storage of stack traces
    2. Sweeping stuck jobs
    3. Handling of cancelled jobs different from failed jobs (machine redeployments)
5. Before and after job hooks
6. Easily run multiple workers to leverage more cores

But on the other hand ARQ is going to be more familiar for most people.

I think in terms of interface the two are quite similar, so perhaps we can have the backend worker library configurable. But this isn't really meant to be a library that would be installed and configured by users, so I'm not really on board with that.

If you feel strongly about ARQ over SAQ that would be enough to sway me TBH.

**Comment by peterschutt** [comment]
NP, let me know your thoughts once you've had a play around with it.
