### ISSUE TITLE
Feature: remove gunicorn dependency

### ISSUE THREAD

**Issue by Goldziher** [starlite-api/starlite-pg-redis-docker#68]
Log messages get duplicated:

```shell
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:29,889 - gunicorn.error - Starting gunicorn 20.1.0
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:29,889 - gunicorn.error - Listening at: http://0.0.0.0:8000 (11)
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:29,889 - gunicorn.error - Using worker: utils.restartable_worker.RestartableUvicornWorker
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:29,891 - gunicorn.error - Booting worker with pid: 13
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:29,911 - gunicorn.error - Booting worker with pid: 14
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:30,056 - uvicorn.error - Application startup complete.
starlite-example-pg-docker-app-1    | INFO - 2022-09-01 16:31:30,058 - uvicorn.error - Application startup complete.
```

**Comment by peterschutt** [comment]
Pretty sure that's just gunicorn running 2 workers - I'm going to strip gunicorn out and just have uvicorn in a single process anyway when I get around to it.

There should be a config in .env for number of workers if you want to check.

**Comment by Goldziher** [comment]
> Pretty sure that's just gunicorn running 2 workers - I'm going to strip gunicorn out and just have uvicorn in a single process anyway when I get around to it.
> 
> There should be a config in .env for number of workers if you want to check.

I'll leave it to you 😁

**Comment by grillazz** [comment]
@peterschutt are you ok to have it on uvicorn ?

**Comment by peterschutt** [comment]
Yep, just straight out uvicorn, but I had a patch pretty close to ready on this - just pushed it up, feel free to comment :+1:
